<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <AssemblyName>RSTT.Whisper.Worker</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\RSTT.Core\RSTT.Core.csproj" />
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime" />
  </ItemGroup>
</Project>
