<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <AssemblyName>RSTT.Whisper.Cuda12.Worker</AssemblyName>
    <DefineConstants>$(DefineConstants);WHISPER_CUDA12</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\RSTT.Whisper.Worker\Program.cs" Link="Program.cs" />
    <ProjectReference Include="..\RSTT.Core\RSTT.Core.csproj" />
    <PackageReference Include="Whisper.net" />
    <PackageReference Include="Whisper.net.Runtime.Cuda12" />
  </ItemGroup>
</Project>
